export const OCCURRENCES: { name: string; code: string }[] = [
  { name: 'Galho Seco', code: 'stick' },
  { name: 'Galho Quebrado', code: 'broken_branch' },
  { name: 'Cipó crescendo', code: 'vine_growing' },
  { name: 'Queimado', code: 'burnt_branch' },
  { name: 'Atingido por raio', code: 'struck_by_lightning' },
  { name: 'Broca', code: 'drill' },
  { name: 'Formigueiro', code: 'anthill' },
  { name: 'Em experimento/teste', code: 'in_experiment' },
  { name: 'Mato na bacia', code: 'weeds_in_the_basin' },
  { name: 'Presença de ácaro', code: 'mites' },
  { name: 'Presença de tripes', code: 'thrips' },
  { name: 'Caixa de colheita vazia perto', code: 'empty_collection_box_near' },
  { name: 'Parada de pulverização/adubação', code: 'fertilization_or_manuring' },
];
