export const OCCURRENCES: { label: string; value: string }[] = [
  { label: 'Galho Seco', value: 'stick' },
  { label: 'Galho Quebrado', value: 'brokenBranch' },
  { label: 'Cipó crescendo no pé', value: 'vineGrowing' },
  { label: 'Queimado', value: 'burntBranch' },
  { label: 'Atingido por raio', value: 'struckByLightning' },
  { label: 'Broca', value: 'drill' },
  { label: 'Formigueiro', value: 'anthill' },
  { label: 'Em experimento/teste', value: 'inExperiment' },
  { label: 'Mato na bacia', value: 'weedsInTheBasin' },
  { label: 'Pulverização/adubação no final do dia', value: 'fertilizationOrManuring' },
  { label: 'Presença de ácaro', value: 'mites' },
  { label: 'Presença de tripes', value: 'thrips' },
  { label: 'Caixa de colheita vazia perto', value: 'emptyCollectionBoxNear' },
];
